import { Calendar, Download } from "lucide-react";
import { motion } from "motion/react";

const TIME_SLOTS = [
  "6:00 AM",
  "6:30 AM",
  "7:00 AM",
  "7:30 AM",
  "8:00 AM",
  "8:30 AM",
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
  "8:30 PM",
  "9:00 PM",
  "9:30 PM",
  "10:00 PM",
];

const FEATURED_SLOTS = [
  "6:00 AM",
  "8:00 AM",
  "10:00 AM",
  "12:00 PM",
  "2:00 PM",
  "4:00 PM",
  "6:00 PM",
  "8:00 PM",
  "10:00 PM",
];

function generatePlannerText(): string {
  const today = new Date();
  const dateStr = today.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [
    "╔══════════════════════════════════════════════╗",
    "║          TIMEMASTER DAILY PLANNER            ║",
    "╚══════════════════════════════════════════════╝",
    "",
    `📅 Date: ${dateStr}`,
    "",
    "🎯 TOP 3 PRIORITIES FOR TODAY:",
    "  1. ___________________________________________",
    "  2. ___________________________________________",
    "  3. ___________________________________________",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "⏰ HOURLY SCHEDULE",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    ...TIME_SLOTS.map(
      (slot) => `  ${slot.padEnd(9)} │ ________________________________`,
    ),
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "💡 NOTES & IDEAS",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "  ________________________________________________",
    "  ________________________________________________",
    "  ________________________________________________",
    "  ________________________________________________",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "🌟 END OF DAY REFLECTION",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "  What went well today?",
    "  ________________________________________________",
    "",
    "  What could I improve tomorrow?",
    "  ________________________________________________",
    "",
    "  Gratitude (3 things):",
    "  1. ___________________________________________",
    "  2. ___________________________________________",
    "  3. ___________________________________________",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "  Generated by TimeMaster | timemaster.caffeine.ai",
    "  Master Your Time. Master Your Life.",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  ];

  return lines.join("\n");
}

export default function DailyPlanner() {
  const handleDownload = () => {
    const content = generatePlannerText();
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const today = new Date().toISOString().split("T")[0];
    const link = document.createElement("a");
    link.href = url;
    link.download = `timemaster-planner-${today}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card rounded-2xl p-6 border border-[oklch(0.25_0.04_255/0.5)] flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-3 mb-4">
        <Calendar className="w-5 h-5 text-[oklch(0.78_0.18_195)]" />
        <div>
          <h3 className="text-lg font-bold font-display neon-text-cyan">
            Daily Planner
          </h3>
          <p className="text-xs text-muted-foreground font-body">
            Printable · Free · No signup
          </p>
        </div>
      </div>

      {/* Preview */}
      <div className="flex-1 bg-[oklch(0.09_0.015_260/0.8)] rounded-xl border border-[oklch(0.25_0.04_255/0.3)] p-4 mb-4 overflow-y-auto max-h-72">
        {/* Header preview */}
        <div className="text-center mb-4">
          <p className="text-xs font-semibold tracking-[0.2em] neon-text-cyan uppercase mb-1">
            TimeMaster
          </p>
          <p className="text-xs text-muted-foreground">Daily Planner</p>
          <p className="text-xs text-muted-foreground mt-1">
            {new Date().toLocaleDateString("en-US", {
              weekday: "long",
              month: "long",
              day: "numeric",
            })}
          </p>
        </div>

        {/* Priorities */}
        <div className="mb-4">
          <p className="text-xs font-bold text-[oklch(0.82_0.2_45)] mb-2 uppercase tracking-wider">
            🎯 Top 3 Priorities
          </p>
          {[1, 2, 3].map((n) => (
            <div key={n} className="flex items-center gap-2 mb-1.5">
              <span className="text-xs text-muted-foreground w-4">{n}.</span>
              <div className="flex-1 h-px bg-[oklch(0.22_0.03_260)]" />
            </div>
          ))}
        </div>

        {/* Time slots preview */}
        <div>
          <p className="text-xs font-bold text-[oklch(0.78_0.18_195)] mb-2 uppercase tracking-wider">
            ⏰ Schedule
          </p>
          {FEATURED_SLOTS.map((slot) => (
            <motion.div
              key={slot}
              className="flex items-center gap-2 mb-1.5"
              whileHover={{ x: 2 }}
            >
              <span className="text-xs font-mono text-[oklch(0.72_0.22_280)] w-16 flex-shrink-0">
                {slot}
              </span>
              <div className="flex-1 h-px bg-[oklch(0.22_0.03_260)]" />
            </motion.div>
          ))}
          <p className="text-xs text-muted-foreground text-center mt-2">
            ... {TIME_SLOTS.length - FEATURED_SLOTS.length} more slots in
            download
          </p>
        </div>
      </div>

      {/* Download button */}
      <button
        type="button"
        onClick={handleDownload}
        className="neon-btn-cyan rounded-xl py-3 font-semibold font-display text-sm flex items-center justify-center gap-2 w-full"
      >
        <Download className="w-4 h-4" />
        Download Today's Planner (.txt)
      </button>
      <p className="text-xs text-muted-foreground text-center mt-2 font-body">
        Free forever. No email required.
      </p>
    </div>
  );
}
