/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TimeBlock = IDL.Record({ 'hours' : IDL.Nat, 'name' : IDL.Text });
export const DailyStatsView = IDL.Record({
  'date' : IDL.Text,
  'timeBlocks' : IDL.Vec(TimeBlock),
});
export const Goal = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeGoal' : IDL.Func([IDL.Text], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'getAllStats' : IDL.Func([], [IDL.Vec(DailyStatsView)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getGoalsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'saveDailyStats' : IDL.Func([IDL.Text, IDL.Vec(TimeBlock)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TimeBlock = IDL.Record({ 'hours' : IDL.Nat, 'name' : IDL.Text });
  const DailyStatsView = IDL.Record({
    'date' : IDL.Text,
    'timeBlocks' : IDL.Vec(TimeBlock),
  });
  const Goal = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeGoal' : IDL.Func([IDL.Text], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'getAllStats' : IDL.Func([], [IDL.Vec(DailyStatsView)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getGoalsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'saveDailyStats' : IDL.Func([IDL.Text, IDL.Vec(TimeBlock)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };