/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStats { 'date' : string, 'timeBlocks' : Array<TimeBlock> }
export interface Goal {
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'description' : string,
}
export interface TimeBlock { 'hours' : bigint, 'name' : string }
export interface _SERVICE {
  'addGoal' : ActorMethod<[string, string], undefined>,
  'completeGoal' : ActorMethod<[string], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'getAllStats' : ActorMethod<[], Array<DailyStats>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getGoalsCount' : ActorMethod<[], bigint>,
  'saveDailyStats' : ActorMethod<[string, Array<TimeBlock>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];